name: pull-requests-workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório e trocar para a branch específica
        uses: actions/checkout@v4

      - name: Instalar JDK
        uses: actions/setup-java@v2
        with:
          distribution: microsoft
          java-version: '17'

      - name: Instalar dependências e compilar
        run: mvn install

      - name: Fazer upload do diretório target
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: target/

  quality:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Clonar repositório e trocar para a branch específica
        uses: actions/checkout@v4

      - name: Baixar os artefatos do job anterior
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Instalar JDK
        uses: actions/setup-java@v2
        with:
          distribution: microsoft
          java-version: '17'

      - name: Executar testes e verificar cobertura de código
        run: mvn test jacoco:report
